version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: labor_policy_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: labor_policy
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - labor_policy_network

  redis:
    image: redis:6.2
    container_name: labor_policy_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - labor_policy_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: labor_policy_backend
    restart: always
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    networks:
      - labor_policy_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: labor_policy_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - labor_policy_network

volumes:
  mysql_data:
  redis_data:

networks:
  labor_policy_network: